apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zxkxa2732-nodejs
  janus-idp.io/tekton: zxkxa2732-nodejs
  backstage.io/kubernetes-id: zxkxa2732-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zxkxa2732-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
