apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zxkxa2732-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zxkxa2732-nodejs 
  name: zxkxa2732-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zxkxa2732-nodejs 
